###Creating a new user
POST http://localhost:8000/api/v1/users/signup
content-type: application/json

{
  "email": "victorojong7@gmail.com",
  "password": "12345",
  "username": "victor ojong moses"
}


### Login user 
POST http://localhost:8000/api/v1/users/login
content-type: application/json

{
  "email": "victorojong78@gmail.com",
  "password": "12345"
}


###Get current user 
GET http://localhost:8000/api/v1/users/currentUser