#Creating a new user
POST http://localhost:8000/api/v1/users/signup
content-type: application/json

{
  "email": "victorojong78090@gmail.com",
  "password": "12345",
  "username": "victor ojong moses"
}



