#Create new booking
POST http://localhost:8000/api/v1/bookings/new
Content-Type: application/json

{
"price": 4000,
"pickUpAddress": "Abuja",
"dropOffAddress": "Calabar",
"calculatedValue": 6700,
"description": "Some kind of description",
"date": "12/02/2023"
}